[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo_tutorial_project"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
modular = ">=25.5.0.dev2025071105,<26"
python = ">=3.11,<3.13"
pygame = ">=2.6.1,<3"

[tasks]
make_build_dir = "mkdir -p build"
build = { cmd = "mojo build src/main.mojo -o build/main", inputs = ["src/main.mojo"], outputs = ["build/main"], depends-on = ["make_build_dir"] }
exe_mojo = "build/main"
execute = [{ task = "build" }, { task = "exe_mojo" }]
clean = "rm -rf build"
